name: vinipoo_p_n
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.1
  shared_preferences: ^2.0.9
  provider: ^6.0.1
  flutter_window_close: ^1.0.0
  dart_ping: ^9.0.1

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/common/logo.png
    - assets/common/guardian.png
    - assets/flags/4x3/xk.svg
    - assets/flags/4x3/xx.svg
    - assets/flags/4x3/ye.svg
    - assets/flags/4x3/yt.svg
    - assets/flags/4x3/za.svg
    - assets/flags/4x3/zm.svg
    - assets/flags/4x3/zw.svg
    - assets/flags/4x3/ad.svg
    - assets/flags/4x3/ae.svg
    - assets/flags/4x3/af.svg
    - assets/flags/4x3/ag.svg
    - assets/flags/4x3/ai.svg
    - assets/flags/4x3/al.svg
    - assets/flags/4x3/am.svg
    - assets/flags/4x3/ao.svg
    - assets/flags/4x3/aq.svg
    - assets/flags/4x3/ar.svg
    - assets/flags/4x3/arab.svg
    - assets/flags/4x3/as.svg
    - assets/flags/4x3/at.svg
    - assets/flags/4x3/au.svg
    - assets/flags/4x3/aw.svg
    - assets/flags/4x3/ax.svg
    - assets/flags/4x3/az.svg
    - assets/flags/4x3/ba.svg
    - assets/flags/4x3/bb.svg
    - assets/flags/4x3/bd.svg
    - assets/flags/4x3/be.svg
    - assets/flags/4x3/bf.svg
    - assets/flags/4x3/bg.svg
    - assets/flags/4x3/bh.svg
    - assets/flags/4x3/bi.svg
    - assets/flags/4x3/bj.svg
    - assets/flags/4x3/bl.svg
    - assets/flags/4x3/bm.svg
    - assets/flags/4x3/bn.svg
    - assets/flags/4x3/bo.svg
    - assets/flags/4x3/bq.svg
    - assets/flags/4x3/br.svg
    - assets/flags/4x3/bs.svg
    - assets/flags/4x3/bt.svg
    - assets/flags/4x3/bv.svg
    - assets/flags/4x3/bw.svg
    - assets/flags/4x3/by.svg
    - assets/flags/4x3/bz.svg
    - assets/flags/4x3/ca.svg
    - assets/flags/4x3/cc.svg
    - assets/flags/4x3/cd.svg
    - assets/flags/4x3/cefta.svg
    - assets/flags/4x3/cf.svg
    - assets/flags/4x3/cg.svg
    - assets/flags/4x3/ch.svg
    - assets/flags/4x3/ci.svg
    - assets/flags/4x3/ck.svg
    - assets/flags/4x3/cl.svg
    - assets/flags/4x3/cm.svg
    - assets/flags/4x3/cn.svg
    - assets/flags/4x3/co.svg
    - assets/flags/4x3/cp.svg
    - assets/flags/4x3/cr.svg
    - assets/flags/4x3/cu.svg
    - assets/flags/4x3/cv.svg
    - assets/flags/4x3/cw.svg
    - assets/flags/4x3/cx.svg
    - assets/flags/4x3/cy.svg
    - assets/flags/4x3/cz.svg
    - assets/flags/4x3/de.svg
    - assets/flags/4x3/dg.svg
    - assets/flags/4x3/dj.svg
    - assets/flags/4x3/dk.svg
    - assets/flags/4x3/dm.svg
    - assets/flags/4x3/do.svg
    - assets/flags/4x3/dz.svg
    - assets/flags/4x3/eac.svg
    - assets/flags/4x3/ec.svg
    - assets/flags/4x3/ee.svg
    - assets/flags/4x3/eg.svg
    - assets/flags/4x3/eh.svg
    - assets/flags/4x3/er.svg
    - assets/flags/4x3/es.svg
    - assets/flags/4x3/es-ct.svg
    - assets/flags/4x3/es-ga.svg
    - assets/flags/4x3/es-pv.svg
    - assets/flags/4x3/et.svg
    - assets/flags/4x3/eu.svg
    - assets/flags/4x3/fi.svg
    - assets/flags/4x3/fj.svg
    - assets/flags/4x3/fk.svg
    - assets/flags/4x3/fm.svg
    - assets/flags/4x3/fo.svg
    - assets/flags/4x3/fr.svg
    - assets/flags/4x3/ga.svg
    - assets/flags/4x3/gb.svg
    - assets/flags/4x3/gb-eng.svg
    - assets/flags/4x3/gb-nir.svg
    - assets/flags/4x3/gb-sct.svg
    - assets/flags/4x3/gb-wls.svg
    - assets/flags/4x3/gd.svg
    - assets/flags/4x3/ge.svg
    - assets/flags/4x3/gf.svg
    - assets/flags/4x3/gg.svg
    - assets/flags/4x3/gh.svg
    - assets/flags/4x3/gi.svg
    - assets/flags/4x3/gl.svg
    - assets/flags/4x3/gm.svg
    - assets/flags/4x3/gn.svg
    - assets/flags/4x3/gp.svg
    - assets/flags/4x3/gq.svg
    - assets/flags/4x3/gr.svg
    - assets/flags/4x3/gs.svg
    - assets/flags/4x3/gt.svg
    - assets/flags/4x3/gu.svg
    - assets/flags/4x3/gw.svg
    - assets/flags/4x3/gy.svg
    - assets/flags/4x3/hk.svg
    - assets/flags/4x3/hm.svg
    - assets/flags/4x3/hn.svg
    - assets/flags/4x3/hr.svg
    - assets/flags/4x3/ht.svg
    - assets/flags/4x3/hu.svg
    - assets/flags/4x3/ic.svg
    - assets/flags/4x3/id.svg
    - assets/flags/4x3/ie.svg
    - assets/flags/4x3/il.svg
    - assets/flags/4x3/im.svg
    - assets/flags/4x3/in.svg
    - assets/flags/4x3/io.svg
    - assets/flags/4x3/iq.svg
    - assets/flags/4x3/ir.svg
    - assets/flags/4x3/is.svg
    - assets/flags/4x3/it.svg
    - assets/flags/4x3/je.svg
    - assets/flags/4x3/jm.svg
    - assets/flags/4x3/jo.svg
    - assets/flags/4x3/jp.svg
    - assets/flags/4x3/ke.svg
    - assets/flags/4x3/kg.svg
    - assets/flags/4x3/kh.svg
    - assets/flags/4x3/ki.svg
    - assets/flags/4x3/km.svg
    - assets/flags/4x3/kn.svg
    - assets/flags/4x3/kp.svg
    - assets/flags/4x3/kr.svg
    - assets/flags/4x3/kw.svg
    - assets/flags/4x3/ky.svg
    - assets/flags/4x3/kz.svg
    - assets/flags/4x3/la.svg
    - assets/flags/4x3/lb.svg
    - assets/flags/4x3/lc.svg
    - assets/flags/4x3/li.svg
    - assets/flags/4x3/lk.svg
    - assets/flags/4x3/lr.svg
    - assets/flags/4x3/ls.svg
    - assets/flags/4x3/lt.svg
    - assets/flags/4x3/lu.svg
    - assets/flags/4x3/lv.svg
    - assets/flags/4x3/ly.svg
    - assets/flags/4x3/ma.svg
    - assets/flags/4x3/mc.svg
    - assets/flags/4x3/md.svg
    - assets/flags/4x3/me.svg
    - assets/flags/4x3/mf.svg
    - assets/flags/4x3/mg.svg
    - assets/flags/4x3/mh.svg
    - assets/flags/4x3/mk.svg
    - assets/flags/4x3/ml.svg
    - assets/flags/4x3/mm.svg
    - assets/flags/4x3/mn.svg
    - assets/flags/4x3/mo.svg
    - assets/flags/4x3/mp.svg
    - assets/flags/4x3/mq.svg
    - assets/flags/4x3/mr.svg
    - assets/flags/4x3/ms.svg
    - assets/flags/4x3/mt.svg
    - assets/flags/4x3/mu.svg
    - assets/flags/4x3/mv.svg
    - assets/flags/4x3/mw.svg
    - assets/flags/4x3/mx.svg
    - assets/flags/4x3/my.svg
    - assets/flags/4x3/mz.svg
    - assets/flags/4x3/na.svg
    - assets/flags/4x3/nc.svg
    - assets/flags/4x3/ne.svg
    - assets/flags/4x3/nf.svg
    - assets/flags/4x3/ng.svg
    - assets/flags/4x3/ni.svg
    - assets/flags/4x3/nl.svg
    - assets/flags/4x3/no.svg
    - assets/flags/4x3/np.svg
    - assets/flags/4x3/nr.svg
    - assets/flags/4x3/nu.svg
    - assets/flags/4x3/nz.svg
    - assets/flags/4x3/om.svg
    - assets/flags/4x3/pa.svg
    - assets/flags/4x3/pc.svg
    - assets/flags/4x3/pe.svg
    - assets/flags/4x3/pf.svg
    - assets/flags/4x3/pg.svg
    - assets/flags/4x3/ph.svg
    - assets/flags/4x3/pk.svg
    - assets/flags/4x3/pl.svg
    - assets/flags/4x3/pm.svg
    - assets/flags/4x3/pn.svg
    - assets/flags/4x3/pr.svg
    - assets/flags/4x3/ps.svg
    - assets/flags/4x3/pt.svg
    - assets/flags/4x3/pw.svg
    - assets/flags/4x3/py.svg
    - assets/flags/4x3/qa.svg
    - assets/flags/4x3/re.svg
    - assets/flags/4x3/ro.svg
    - assets/flags/4x3/rs.svg
    - assets/flags/4x3/ru.svg
    - assets/flags/4x3/rw.svg
    - assets/flags/4x3/sa.svg
    - assets/flags/4x3/sb.svg
    - assets/flags/4x3/sc.svg
    - assets/flags/4x3/sd.svg
    - assets/flags/4x3/se.svg
    - assets/flags/4x3/sg.svg
    - assets/flags/4x3/sh.svg
    - assets/flags/4x3/sh-ac.svg
    - assets/flags/4x3/sh-hl.svg
    - assets/flags/4x3/sh-ta.svg
    - assets/flags/4x3/si.svg
    - assets/flags/4x3/sj.svg
    - assets/flags/4x3/sk.svg
    - assets/flags/4x3/sl.svg
    - assets/flags/4x3/sm.svg
    - assets/flags/4x3/sn.svg
    - assets/flags/4x3/so.svg
    - assets/flags/4x3/sr.svg
    - assets/flags/4x3/ss.svg
    - assets/flags/4x3/st.svg
    - assets/flags/4x3/sv.svg
    - assets/flags/4x3/sx.svg
    - assets/flags/4x3/sy.svg
    - assets/flags/4x3/sz.svg
    - assets/flags/4x3/tc.svg
    - assets/flags/4x3/td.svg
    - assets/flags/4x3/tf.svg
    - assets/flags/4x3/tg.svg
    - assets/flags/4x3/th.svg
    - assets/flags/4x3/tj.svg
    - assets/flags/4x3/tk.svg
    - assets/flags/4x3/tl.svg
    - assets/flags/4x3/tm.svg
    - assets/flags/4x3/tn.svg
    - assets/flags/4x3/to.svg
    - assets/flags/4x3/tr.svg
    - assets/flags/4x3/tt.svg
    - assets/flags/4x3/tv.svg
    - assets/flags/4x3/tw.svg
    - assets/flags/4x3/tz.svg
    - assets/flags/4x3/ua.svg
    - assets/flags/4x3/ug.svg
    - assets/flags/4x3/um.svg
    - assets/flags/4x3/un.svg
    - assets/flags/4x3/us.svg
    - assets/flags/4x3/uy.svg
    - assets/flags/4x3/uz.svg
    - assets/flags/4x3/va.svg
    - assets/flags/4x3/vc.svg
    - assets/flags/4x3/ve.svg
    - assets/flags/4x3/vg.svg
    - assets/flags/4x3/vi.svg
    - assets/flags/4x3/vn.svg
    - assets/flags/4x3/vu.svg
    - assets/flags/4x3/wf.svg
    - assets/flags/4x3/ws.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

