# Generated by Django 5.0.6 on 2024-07-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnconfig', '0003_vpnconfig_remove_config_location_remove_config_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnconfig',
            name='country_code',
            field=models.CharField(default='SG', max_length=2),
        ),
    ]
