# Generated by Django 5.0.6 on 2024-07-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnconfig', '0004_vpnconfig_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnconfig',
            name='country_code',
            field=models.CharField(default='sg', max_length=2),
        ),
    ]
