# Generated by Django 5.0.6 on 2024-07-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnconfig', '0005_alter_vpnconfig_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnconfig',
            name='userid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vpnconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
