# Generated by Django 5.0.6 on 2024-07-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnconfig', '0006_vpnconfig_userid_alter_vpnconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnconfig',
            name='userid',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
