# Generated by Django 5.0.6 on 2024-07-27 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpnconfig.location')),
                ('users', models.ManyToManyField(to='vpnconfig.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
