# Generated by Django 5.0.6 on 2024-07-27 03:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnconfig', '0002_config_delete_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnConfig',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='config',
            name='location',
        ),
        migrations.RemoveField(
            model_name='config',
            name='users',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
